package com.ui;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;

import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class GuestLogin extends javax.swing.JFrame {

	/**
	 * Creates new form NewJFrame
	 */

	private static String[] LevelTermArray = { "Level-1,Term-1",
			"Level-1,Term-2", "Level-2,Term-1", "Level-2,Term-2",
			"Level-3,Term-1", "Level-3,Term-2", "Level-4,Term-1",
			"Level-4,Term-2" };
	
	private int selectedLevelTermSerial = 0;

	public GuestLogin() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		welcomeLabel = new javax.swing.JLabel();
		subGuestLabel = new javax.swing.JLabel();
		levelTermComboBox = new JComboBox();
		selectLevelTermLabel = new javax.swing.JLabel();
		goGuestMenuButton = new javax.swing.JButton();
		backtoLoginButton = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		welcomeLabel.setFont(new java.awt.Font("Lucida Bright", 1, 24)); // NOI18N
		welcomeLabel.setText("Welcome to BUET CSE Mini Moodle");

		subGuestLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
		subGuestLabel.setForeground(new java.awt.Color(204, 0, 0));
		subGuestLabel.setText("(Guest View)");

		levelTermComboBox.setFont(new java.awt.Font("Times New Roman", 1, 17)); // NOI18N
		levelTermComboBox = new JComboBox(LevelTermArray);
		levelTermComboBox.addItemListener(new ItemListener() {

			@Override
			public void itemStateChanged(ItemEvent event) {
				// TODO Auto-generated method stub
				if (event.getStateChange() == ItemEvent.SELECTED) {
					try {
						/*System.out.println(LevelTermArray[levelTermComboBox
								.getSelectedIndex()]);*/
						selectedLevelTermSerial = levelTermComboBox.getSelectedIndex();
						//System.out.println(selectedLevelTerm);
					}

					catch (Exception e) {
						e.printStackTrace();
					}
				}
			}
		});

		selectLevelTermLabel
				.setFont(new java.awt.Font("Times New Roman", 3, 17)); // NOI18N
		selectLevelTermLabel.setText("Select Level and Term");

		goGuestMenuButton.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
		goGuestMenuButton.setText("Go>>>");
		goGuestMenuButton
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						goGuestMenuButtonActionPerformed(evt);
					}
				});

		backtoLoginButton.setFont(new java.awt.Font("Lucida Sans", 1, 11)); // NOI18N
		backtoLoginButton.setText("<<< Back");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGap(76, 76, 76)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(
														levelTermComboBox,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(welcomeLabel)
												.addComponent(
														selectLevelTermLabel))
								.addContainerGap(80, Short.MAX_VALUE))
				.addGroup(
						javax.swing.GroupLayout.Alignment.TRAILING,
						layout.createSequentialGroup()
								.addContainerGap(
										javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														javax.swing.GroupLayout.Alignment.TRAILING,
														layout.createSequentialGroup()
																.addComponent(
																		subGuestLabel,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		98,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addGap(237,
																		237,
																		237))
												.addGroup(
														javax.swing.GroupLayout.Alignment.TRAILING,
														layout.createSequentialGroup()
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.TRAILING,
																				false)
																				.addComponent(
																						goGuestMenuButton,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						Short.MAX_VALUE)
																				.addComponent(
																						backtoLoginButton,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						101,
																						Short.MAX_VALUE))
																.addGap(91, 91,
																		91)))));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGap(27, 27, 27)
								.addComponent(welcomeLabel,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										53,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(subGuestLabel,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										31,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(34, 34, 34)
								.addComponent(selectLevelTermLabel)
								.addGap(18, 18, 18)
								.addComponent(levelTermComboBox,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED,
										67, Short.MAX_VALUE)
								.addComponent(goGuestMenuButton,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										41,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(53, 53, 53)
								.addComponent(backtoLoginButton,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										31,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(52, 52, 52)));

		pack();
	}// </editor-fold>

	private void goGuestMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		GuestMenu a = new GuestMenu(selectedLevelTermSerial);
		a.setVisible(true);
		a.setSize(300, 380);
		a.setLocationRelativeTo(null);
		a.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		this.setVisible(false);
	}

	public static void main(String args[]) {
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
					.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(GuestLogin.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(GuestLogin.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(GuestLogin.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(GuestLogin.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new GuestLogin().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify
	private javax.swing.JButton backtoLoginButton;
	private javax.swing.JButton goGuestMenuButton;
	private JComboBox levelTermComboBox;
	private javax.swing.JLabel selectLevelTermLabel;
	private javax.swing.JLabel subGuestLabel;
	private javax.swing.JLabel welcomeLabel;
	// End of variables declaration
}
