/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

//package rough;
import java.io.*;
import java.net.Socket;
import static com.ui.generateIP.*;
import java.util.Scanner;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;
/**
 *
 * @author User
 */
public class Notice extends javax.swing.JFrame{

    /**
     * Creates new form Notice
     */
    public TeacherElements stp;
    public String[][] allsub={{"CSE-100","EEE-163","EEE-164","MATH-141","ME-160","ME-165","PHY-109","PHY-102"},{"CSE-103","CSE-105","CSE-106","Chem-113","Chem-114","HUM-175","HUM-272","MATH-143"},{"CSE-201","CSE-202","CSE-203","CSE-204","CSE-205","CSE-206","EEE-263","EEE-264","MATH-241"},{"CSE-207","CSE-208","CE-209","CSE-210","CSE-211","CSE-214","EEE-269","EEE-270","MATH-243"},{"CSE-300","CSE-303","CSE-304","CSE-305","CSE-307","CSE-308","CSE-309","CSE-310","CSE-311"},{"CSE-301","CSE-313","CSE-314","CSE-315","CSE-316","CSE-317","CSE-321","CSE-322","CSE-324"},{"CSE-400","CSE-401","CSE-402","CSE-403","CSE-404","Option-1","Option-2","IPE-493"},{"CSE-400","CSE-409","CSE-410","Option-3","Option-3 Sessional","HUM-275","HUM-371"}};
    public String[] Year=new String[100];
    public String[] Day=new String[31];
    public Notice(TeacherElements a) {
        super("Notice Maker");
        stp = a;
        System.out.println(stp.getUserID());
        int j = 1990;
        for (int i = 0; i < Year.length; ++i) {
            Year[i] = Integer.toString(j);
            j++;
        }

        j = 1;
        for (int i = 0; i < Day.length; ++i) {
            Day[i] = Integer.toString(j);
            j++;
        }

        initComponents();
        for (int i = 0; i < Year.length; ++i) {
            yearcombo.addItem(Year[i]);
        }

        for (int i = 0; i < Day.length; ++i) {
            daycombo.addItem(Day[i]);
        }
        System.out.println(allsub.length);
        coursecombo.removeAllItems();
        for (j = 0; j < allsub[0].length; ++j) {
            coursecombo.addItem(allsub[0][j]);
        }

         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        monthcombo = new javax.swing.JComboBox();
        daycombo = new javax.swing.JComboBox();
        yearcombo = new javax.swing.JComboBox();
        post = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        LTcombo = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        Syllabus = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        coursecombo = new javax.swing.JComboBox();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        typecombo = new javax.swing.JComboBox();

        jLabel7.setText("jLabel7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jLabel3.setText("Year");

        jLabel2.setText("Day");

        jLabel1.setText("Month");

        monthcombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));

        post.setText("Post Notice");
        post.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                postFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                postFocusLost(evt);
            }
        });
        post.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                postActionPerformed(evt);
            }
        });

        jLabel4.setText("Level/Term");

        LTcombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Level-1,Term-1", "Level-1,Term-2", "Level-2,Term-1", "Level-2,Term-2", "Level-3,Term-1", "Level-3,Term-2", "Level-4,Term-1", "Level-4,Term-2", " " }));
        LTcombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                LTcomboItemStateChanged(evt);
            }
        });
        LTcombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LTcomboActionPerformed(evt);
            }
        });

        Syllabus.setColumns(20);
        Syllabus.setRows(5);
        Syllabus.setText("(Post Syllabus)");
        Syllabus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SyllabusMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Syllabus);

        jLabel5.setText("Course");

        coursecombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel6.setText("Exam Type:");

        typecombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "CT", "Online", "Offline", "Assignment" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1))
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(LTcombo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(coursecombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(61, 61, 61))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(post, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 16, Short.MAX_VALUE))))
            .addComponent(jSeparator2)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(monthcombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(daycombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(yearcombo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(typecombo, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(monthcombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(daycombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yearcombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LTcombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(coursecombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(typecombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(post, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_formComponentShown

    private void postActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_postActionPerformed
        int totalfile = -2;
        try {
            Socket clientsocket = new Socket(getglobal(), 12345);
            PrintWriter pw = new PrintWriter(clientsocket.getOutputStream());
            pw.println("totalfile");
            pw.flush();
            Socket newclientsocket = new Socket(getglobal(), 30006);
            Scanner sc = new Scanner(newclientsocket.getInputStream());
            while (true) {
                totalfile = sc.nextInt();
                if (totalfile >= 0) {
                    break;
                }
            }
            System.out.println(totalfile+"file er sonkha");
        } catch (Exception e) {
            e.printStackTrace();
        }
        StudentElements std = new StudentElements("", "", "",
                "", "", "", "", "");
        String month = monthcombo.getSelectedItem().toString();
        String day = daycombo.getSelectedItem().toString();
        String year = yearcombo.getSelectedItem().toString();
        String syllabus = Syllabus.getText();
        int errorflag = 0;
        if (syllabus.length() == 0 || syllabus.equals("(Post Syllabus)")) {
            errorflag = 1;
            JOptionPane.showMessageDialog(null, "Please Type Syllabus");
        }
        if (errorflag == 0) {
            String LT = LTcombo.getSelectedItem().toString();
            String course = coursecombo.getSelectedItem().toString();
            String xmtyp = typecombo.getSelectedItem().toString();
            noticeClass xmnotice = new noticeClass(month, day, year, LT, course, syllabus, xmtyp);
            System.out.println(xmnotice);

            try {
                //StudentElements std;
                Socket clientsocket = new Socket(getglobal(), 12345);
                PrintWriter pw = new PrintWriter(clientsocket.getOutputStream());
                pw.println("getnotice");
                pw.flush();
                Socket newclientsocket = new Socket(getglobal(), 30005);
                for (int i = 0; i < totalfile; ++i) {
                    ObjectInputStream ois = new ObjectInputStream(newclientsocket.getInputStream());
                    System.out.println("esechi");
                    std = (StudentElements)ois.readObject();
                        
                    if (std.getLT().equals(LTcombo.getSelectedItem().toString())) {
                        std.AddNoti(xmnotice);
                    }
                    ObjectOutputStream oos = new ObjectOutputStream(newclientsocket.getOutputStream());
                    oos.writeObject(std);
                }
                newclientsocket.close();

            } catch (Exception e) {
                System.out.println("Exception during deserialization: " + e);
                e.printStackTrace();
                
            }
            

            setVisible(false);
            TeacherInfo a = new TeacherInfo(stp.getUserID());
            a.setLocationRelativeTo(null);
            a.setVisible(true);
            a.setResizable(false);
            a.setSize(500, 350);
            a.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);

        }

    

       
    }//GEN-LAST:event_postActionPerformed

    private void LTcomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LTcomboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LTcomboActionPerformed

    private void SyllabusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SyllabusMouseClicked
        Syllabus.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_SyllabusMouseClicked

    private void LTcomboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_LTcomboItemStateChanged
        coursecombo.removeAllItems();
        int i;
        i=LTcombo.getSelectedIndex();
        for(int j=0;j<allsub[i].length;++j){
            coursecombo.addItem(allsub[i][j]);
        }// TODO add your handling code here:
    }//GEN-LAST:event_LTcomboItemStateChanged

    private void postFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_postFocusGained
            //Syllabus.setText("Focused");        // TODO add your handling code here:
    }//GEN-LAST:event_postFocusGained

    private void postFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_postFocusLost
      // Syllabus.setText("Focus lost");     // TODO add your handling code here:Syllabus.setText("Focused");    
    }//GEN-LAST:event_postFocusLost

    /**
     * @param args the command line arguments
     */
   /* public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
      /*  try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Notice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Notice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Notice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Notice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
     /*   java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Notice().setVisible(true);
            }
        });
    }'*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox LTcombo;
    private javax.swing.JTextArea Syllabus;
    private javax.swing.JComboBox coursecombo;
    private javax.swing.JComboBox daycombo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JComboBox monthcombo;
    private javax.swing.JButton post;
    private javax.swing.JComboBox typecombo;
    private javax.swing.JComboBox yearcombo;
    // End of variables declaration//GEN-END:variables
}
